title: MZ Max
description: The Ultimate Machine Learning and Deep Learning Platform
url: "https://MO-Elsamahy.github.io"
baseurl: "/mz-max"

# Theme - Using default GitHub Pages theme
theme: jekyll-theme-minimal

# Plugins (only GitHub Pages compatible ones)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: MZ Max Development Team
social:
  name: MZ Max
  links:
    - https://github.com/MO-Elsamahy/mz-max

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Code highlighting
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
  - "*.gemspec"
  - "*.gem"

# Permalink structure
permalink: /:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
